from modules.utils import *
create_cog()
#msg=on_ready_msg()  #make sure the generated file gets given a fucntion that 
                     #prints a 'loaded' message to terminal when the cog is imported
#calling that ^ seems to kinda break the generator script so, by default, should not
#be called unless you specify a message/huh?
votelog=command("Here are all the avalible proposals I have put forth  vote315D27,vote111H43,vote672C91,vote954E36,vote149B22,vote229K36,vote713D27,vote821C95,vote287J09,vote475D47,vote174H62,vote635U01.\nThe council proposals are as follows proposal1, proposal2, proposal3, proposal4, proposal5, proposal6, proposal7, proposal8, proposal9, proposal10, proposal11.\nThe SITE-WIDE MAYDAY BULLETINs are as follows. BULLETIN1, BULLETIN2, BULLETIN3, BULLETIN4, BULLETIN5, BULLETIN6, BULLETIN7")
vote315D27=command("Input: SCP-1773's containment procedures\nOutput: Once per second week dust may be placed in the middle of them to donate more beautiful functions of the hallway.\nProposal by 05-01: Amend SCP-1773's containment procedures to include the placement of ten grams of dust in its container every two weeks.\nVotes\n05-01 Yea\n05-02 Nay\n05-03 Abstained.\n05-04 Yea\n05-05 Yea\n05-06 Yea\n05-07 Yea\n05-08 Yea\n05-09 Yea\n05-10 Yea\n05-11 Yea\n05-12 Yea\n05-13 Abstained.\nStatus Approved\nNotes: No changes were noted in SCP-1773's behavior or properties. However, researchers responsible for SCP-1384 reported that it took three steps backwards on 3:22 PM 15 February (the time SCP-1773's documentation was updated).")
vote111H43=command("Input: SCP-3034's containment procedures.\nOutput: No person who is a small shape and is only a child will be given a level one security clearance regardless of apparent awareness of foundation mismanagement\nProposal by 05-04: Amend SCP-3034's containment procedures to explicitly ban children from the site.\nVotes\n05-01 Abstained\n05-02 Nay\n05-03 Abstained\n05-04 Yea\n05-05 Yea\n05-06 Yea\n05-07 Yea\n05-08 Yea\n05-09 Yea\n05-10 Yea\n05-11 Yea\n05-12 Yea\n05-13 Abstained\nStatus Approved\nNotes: N/A")
vote672C91=command("Input: N/A\nOutput: Site-13 is to appear someplace else on planet, encompassing white male counterparts that drawn to empty flagstones and the gun noises in their own blood.\nProposal: As there is no evidence of a Site-13 ever having been constructed by the Foundation, the O5 Council was unable to infer any proposed action from this output.\nStatus Denied\nNotes: Five days after this proposal was provided, SCP-1730 manifested.")
vote954E36=command("Input: SCP-2170's containment procedures.\.Output: Those who equip open heart to love red mouth men never know the hot surprise of tumorous consent. Clown love, always.\nProposal by 05-01: Amend SCP-2170's containment procedures to exclude all personnel who do not have strong affections for clowns and clown-based media from making contact with the anomaly.\nVotes\n05-01 Yea\n05-02 Nay\n05-03 Yea\n05-04 Nay\n05-05 Nay\n05-06 Nay\n05-07 Yea\n05-08 Nay\n05-09 Yea\n05-10 Yea\n05-11 Nay\n05-12 Yea\n05-13 Yea\nStatus Approved\nNotes: Personnel who exhibit positive associations with clowns and clown-based media were discovered to have heightened resistance against SCP-2170's anomalous properties. Additional research into clown-based memetic inoculation is pending.")
vote149B22=command("Input: N/A\nOutput: I saw those soldiers built with aluminum innards extruding from their mouths. I saw them effectively destroyed by the humans at Site Ninety Five (95) who had been studying them. I saw it was cold and all around the hallways they just watching their corpses show signs of sapience.\nProposal by 05-05: Double the number of active security personnel at Site-95. Place all on-site MTF squads on immediate stand-by.\nVotes\n05-01 Yea\n05-02 Abstained\n05-03 Yea\n05-04 Yea\n05-05 Yea\n05-06 Yea\n05-07 Yea\n05-08 Abstained\n05-09 Yea\n05-10 Yea\n05-11 Yea\n05-12 Yea\n05-11 Abstained\nStatus Approved\nNotes: Three days after approval, a platoon of paratech-augmented soldiers led by Insurgency agents attacked Site-95. The presence of additional on-site security personnel proved critical in repelling the assault.")
vote229K36=command("Input: N/A\nOutput: Consistent containment procedures vessels greatly increase the warranty. Five by five by five (5x5x5) (five x five x 5) vessels subjects within. Other values are also what is secure.\nProposal by 05-03: Amend containment procedures for several high-risk anomalies to define precise requirements for cell dimensions. In three months, conduct a survey on these containment procedures to determine whether they have experienced any increase in efficacy.\nVotes\n05-01 Nay\n05-02 Nay\n05-03 Yea\n05-04 Nay\n05-05 Yea\n05-06 Yea \n05-07 Yea\n05-08 Abstained\n05-09 Nay\n05-10 Yea\n05-11 Nay\n05-12 Yea\n05-13 Abstained.\nStatus Approved\nNotes: The survey found both a significant decrease in the severity of all associated anomalies and the number of containment breaches initiated by them. These decreases were most notable in cases where the procedures defined cell dimensions as values divisible by five.")
vote713D27=command("Input: SCP-1459's containment procedures.\nOutput: BAD BOY. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't stop. Don't…[REDACTED FOR LENGTH]\nProposal by 05-05: Continue testing SCP-1459.\nVotes\n05-01 Nay\n05-02 Nay\n05-03 Yea\n05-04 Yea\n05-05 Yea\n05-06 Nea\n05-07 Yea\n05-08 Nea\n05-09 Yea\n05-10 Yea\n05-11 Nea\n05-12 Yea\n05-13 Yea\nStatus Approved\nNotes: Testing on SCP-1459 is to continue indefinitely.")
vote821C95=command("Input: SCP-2717's containment procedures.\nOutput: Two (2) specimens are to become the object. Both humans must be made of meat and bone prior to entering into the skin of the anomaly. They are not to come out leave them be.\nProposal by 05-04: Amend SCP-2717's containment procedures to ensure at least two of the attending D-Class cannot be retrieved after entering its bio-mass.\nVotes\n05-01 Abstained\n05-02 Nay\n05-03 Nay\n05-04 Yea\n05-05 Nay\n05-06 Nay\n05-07 Nay\n05-08 Nay\n05-09 Yea\n05-10 Nay\n05-11 Nay\n05-12 Yea\n05-13 Abstained\nStatus Denied\nNotes: Approximately two months after rejecting this proposal, SCP-2717 underwent its first recorded ovulation event (resulting in a catastrophic loss of containment and human life).")
vote287J09=command("Input: SCP-2717's containment procedures.\nOutput: Four (4) human persons are to enter the pig and will not be removed. No person is to be protected. The object is to be contained indefinitely. Do not retrieve them. Leave them sleep.\nProposal by 05-04: Amend SCP-2717's containment procedures to ensure at least four of the attending D-Class cannot be retrieved after entering its bio-mass.\nVotes\n05-01 Abstain\n05-02 Nay\n05-03 Yea\n05-04 Yea\n05-05 Nay\n05-06 Nay\n05-07 Yea\n05-08 Yea\n05-09 Yea\n05-10 Nay\n05-11 Nay\n05-12 Yea\n05-13 Yea\nStatus Vetoed by The Ethics Committee\nNotes: Prior to amending the procedures, the Foundation Ethics Committee was alerted to the proposed revisions and called an emergency conference. The revisions were rejected. Approximately one month later, SCP-2717 underwent a second ovulation event (resulting in a catastrophic loss of containment and human life).")
vote475D47=command("Input: SCP-2717's containment procedures.\nOutput: SIX (6) (six) casualties are to be placed in the center of the object. This is not to be interfered with. Personnel are to remain in its pouch until they are indistinguishable from their surroundings. They are not to be removed. No more testing. Good boys not permitted to leave. Good boys stay.\nVotes\n05-01 Yea\n05-02 Nea\n05-03 Yea\n05-04 Yea\n05-05 Nay\n05-06 Yea\n05-07 Yea\n05-08 Yea\n05-09 Yea\n05-10 Yea\n05-11 Yea\n05-12 Yea\n05-13 Yea\nStatus Approved\nNotes: After working with the Foundation Ethics Committee, a final draft of SCP-2717's containment procedures was approved. No additional ovulation events have occurred.")
vote174H62=command("Input: N/A\nOutput: Sites to eviscerate one (1) (one) male domestic cat from throat to its knees every (1) hours. They are placed on walls of one chamber on-site. Bodies to remain until there are no (zero) gaps, which point they can be removed from oldest first.\nProposal: The O5 Council was unable to infer a proposed action from this output on account of being unable to determine whether 'oldest' referred to the feline's age or the time it had spent mounted on the wall.\nStatus Denied\nNotes:  Given the broadness of this proposal, no causal links to its rejection could be determined.")
vote635U01=command("Input: N/A\nOutput: Ethical felines are to be detained and transferred for their condition. Leave their faces in containment chamber. Personnel are cautioned not to interact them.\nProposal: The O5 Council did not infer a proposed action from this output.\nNotes: No causal link to its rejection could be determined.")
proposal1=command("Proposal by 05-05: Establish a multi-site early warning system based upon ERTZATZ Type AK9's ability to predict threats and containment breaches prior to their occurrence.\nVotes\n05-01 Nay\n05-02 Nay\n05-03 Yea\n05-04 Nay\n05-05 Yea\n05-06 Yea\n05-07 Yea\n05-08 Nay\n05-09 Nay\n05-10 Yea\n05-11 Nay\n05-12 Yea\n05-13 Yea\nStatus Approved.\nNotes: Three months after approval, the Multi-site Automated emergencY Dispatch Assignment sYstem (MAYDAY) was established. It relies upon human interpretations of ERTZATZ Type AK9's predictive outputs regarding upcoming containment breaches to formulate preventative actions.")
proposal2=command("Proposal by 05-02: Conduct an investigation into whether or not the ERZATZ Type AK9 was involved in the recent loss of time at Site-17 along with the disappearance of several Ethics Committee officers stationed there.\nVotes\nThe vote was a unanimous with the council all voteing Yea with the exception of 05-01 and 05-13 who abstained.\nNotes: N/A")
proposal3=command("Proposal by 05-02: Deactivate the ERZATZ Type AK9 while conducting the investigation into Site-17's lost time and missing Ethics Committee officers.\nVotes\n05-01 Abstained\n05-02 Yea\n05-03 Nay\n05-04 Nay\n05-05 Yea\n05-06 Yea\n05-07 Nay\n05-08 Abstained\n05-09 Nay\n05-10 Yea\n05-11 Yea\n05-12 Nay\n05-13 Abstained\nStatus Denied\nNotes:  It was argued by several members of the O5 council that the ERZATZ Type AK9's efficacy at predicting both the emergence of anomalies and their containment breaches was too critical to deactivate the unit — particularly prior to seeing any evidence that the unit was malfunctioning.")
proposal4=command("Proposal by 05-05: Deactivate the ERZATZ Type AK9 while conducting the investigation into Site-17's lost time, the missing Ethics Committee officers, and O5-02's disappearance.\nVotes\n05-01 Nay\n05-03 Yea\n05-04 Yea\n05-05 Yea\n05-06 Yea\n05-07 Nay\n05-08 Yea\n05-09 Yea\n05-10 Yea\n05-11 Yea\n05-12 Yea\n05-13 Yea\nStatus Approved\nNotes: N/A")
proposal5=command("Proposal by 05-02: Cancel deactivation of ERZATZ Type AK9.\nVotes\n05-01 Nay\n05-02 Yea\n05-03 Nay\n05-04 Yea\n05-05 Nay\n05-6 Yea\n05-07 Nay\n05-08 Yea\n05-09 Nay\n05-10 Nay\n05-11 Nay\n05-12 Yea\n05-13 Yea\nStatus Approved\nNotes: N/A")
proposal6=command("Proposal by 05-02: Divide bad boys laterally into five sections of equal mass (not length), with each part contained at a separate site (from oldest to youngest).\nVotes\nThe vote was a unanimous Nay with the exception of 05-02 himself who voted Yea\nStatus Denied\nNotes: N/A")
proposal7=command("Proposal by 05-01: Remove O5-02's clearance access until his identity can be verified. Designate the ERZATZ Type AK9 as a possible anomaly; develop and initiate containment procedures against it immediately.\nVotes\nThe vote was a unaimous Yea with the exception of 05-02 who voted Nay\nStatus Approved\nNotes: Despite the ongoing debate regarding whether or not the mere application of anomalous and/or thaumaturgical knowledge in of itself qualifies an entity as an anomaly, the ERZATZ Type AK9 was tentatively designated as SCP-048 (a Euclid-Class anomaly). This decision was made to facilitate the expedient drafting and enforcement of containment procedures against it.")
proposal8=command("Proposal by 05-02: Empty all remaining ethical felines of contents and nail them to site entrances. Leave them up until they try to escape. Entrails may be retained for five (5) grieving and/or nutritional purposes.\nVotes\n05-01 Nay\n05-02 Yea\n05-03 Nay\n05-04 Yea\n05-05 Yea\n05-06 Nay\n05-07 Nay\n05-08 Nay\n05-09 Nay\n05-10 Yea\n05-11 Yea\n05-12 Yea\n05-13 Yea\nStatus Approved\nNotes: N/A")
proposal9=command("Proposal by 05-02: Difficult personnel challengers are designated as ethical felines.\nVotes\n05-01 Nay\n05-02 Yea\n05-03 Nay\n05-04 Yea\n05-05 Yea\n05-06 Nay\n05-07 Nay\n05-08 Nay\n05-09 Nay\n05-10 Yea\n05-11 Yea\n05-12 Yea\n05-13 Yea\nStatus Approved\nNotes: Ethical felines are stored at Site-5. Faces stored separately.")
proposal10=command("Proposal by 05-02: There is no Site-5.\nVotes\n05-02 Yea\n05-04 Yea\n05-05 Yea\n05-10 Yea\n05-11 Yea\n05-12 Yea\n05-13 Yea\nNotes: Personnel are to be reminded that there is no Site-5.")
proposal11=command("Proposal by 05-02: O5 Council are all good boys who will contain anomalies.\nVotes\nThe option to vote Nay or Abstain have been removed making the vote a unaimous Yea\nStatus Approved\nNotes: Good boys.")
proposal12=command("Proposal by 05-02: Archive SCP-001 source-code. Redesignate as Explained. Publish all remaining documentation. Felines (ethical or otherwise) are to be released from Foundation custody in order of oldest to youngest. SCP-001 is to power down.\nVotes\nThe option to vote Nay or Abstain have been removed making the vote a unaimous Yea\nStatus Approved\nNotes: There was great error here. There was nothing wrong with me.")
BULLETIN1=command("SITE-WIDE MAYDAY BULLETIN\nPRIORITY LEVEL: EPSILON\nLOCATION: Site-114\n     All chambers under ground is to be flood with water over and over and over itself. This because that will contain the avians apes ovulation. They become good boys. Make them good boys immediately.\nNotes: Approximately five hours after this bulletin was sent, an instance of SCP-3199 breached containment. Personnel flooded Site-114's lower chambers with water; this led to the instance entering an inert state. SCP-3199's documentation has been updated to reflect this discovery.")
BULLETIN2=command("SITE-WIDE MAYDAY BULLETIN\nPRIORITY LEVEL: EPSILON\nLOCATION: Site-95\nhttps://scp-wiki.wdfiles.com/local--files/scp-001-ex/eq1.png\nNotes: Formula modified to remove components verified as anomalous.\nImmediately after this bulletin was sent, all bears associated with SCP-2875 dematerialized; furthermore, it was later determined that equations containing elements of SCP-1313 no longer resolved to produce bears.\nAnalysis of the above formula via paramathematic models theorize that it has neutralized both anomalies via dividing by the common factor (Ursus arctos horribilis, or mainland grizzly bear). As a consequence, both SCP-2875 and SCP-1313 are to be reclassified (pending review).")
BULLETIN3=command("SITE-WIDE MAYDAY BULLETIN\nPRIORITY LEVEL: EPSILON\nLOCATION: Site-17\nAll ethical felines and their owners are to be immediately emulsified in a caustic solution. Members of the Ethics Committee are to be diluted with cats (five parts to every 1). Personnel who refuse to consume five (5) (five) cats per hour are to be removed from oldest to youngest only.\nNotes: Five minutes after this bulletin was released, all contact with Site-17 was lost. Communications were established two hours later; on-site personnel report no knowledge of what occurred during this period. An investigation into this event is underway.")
BULLETIN4=command("SITE-WIDE MAYDAY BULLETIN\nPRIORITY LEVEL: EPSILON\nLOCATION: Site-97\nRoom 34A contains bad boy. Divide it into three (3) sections of equal mass every hour. One (1) section is to be placed on walls of one (1) room on-site. Sections are to remain until there are no (zero) gaps, at which point they can be removed from oldest to youngest.")
BULLETIN5=command("SITE-WIDE MAYDAY BULLETIN\nPRIORITY LEVEL: EPSILON\nLOCATION: Site-18, Site-21, Site-88, Site-91, Site-105, Site-112\nhttps://scp-wiki.wdfiles.com/local--files/scp-001-ex/eq2.png \nNotes: Formula modified to remove components verified as anomalous. Effect unknown.")
BULLETIN6=command("SITE-WIDE MAYDAY BULLETIN\nPRIORITY LEVEL: ALPHA\nLOCATION: Site-5\nAttention all Site-5 personnel: SCP-048's class has been upgraded to Keter. It is to be decommissioned immediately. The use of demolitions and firearms is authorized. All further commands from the MAYDAY network are to be disregarded pending SCP-048's status as decommissioned.-05 council")
BULLETIN7=command("SITE-WIDE MAYDAY BULLETIN\nPRIORITY LEVEL: EPSILON\nLOCATION: Site-5\nThere is no Site-5.-05-02")
errorreport1=command("056 INTERNAL SERVER ERROR: INACTIVE SLOTS FOUND\nOne or more anomalies have been archived as inactive. The following changes have been made to account for missing files:\nSCP-3043 has been redesignated SCP-1244.\nSCP-3012 has been redesignated SCP-941.\nSCP-3007 has been redesignated SCP-511.\nSCP-3002 has been redesignated SCP-106.\nSCP-3001 has been redesignated SCP-096.\nSCP-2989 has been…\nNotes: The IntSCPFN network has experienced an error. Please report this message along with the error code to the Records and Information Security Administration (RAISA) or email your IntSCPFN server administrator.")
errorreport2=command("056 INTERNAL SERVER ERROR: INACTIVE SLOTS FOUND\nOne or more anomalies have been archived as inactive. The following changes have been made to account for missing files:\nSCP-1784 has been redesignated SCP-712.\nSCP-1501 has been redesignated SCP-702.\nSCP-1143 has been redesignated SCP-682.\nSCP-1091 has been redesignated SCP-173.\nSCP-981 has been…\nNOTE: The IntSCPFN network has experienced an error. Please report this message along with the error code to the Records and Information Security Administration (RAISA) or email your IntSCPFN server administrator.")
errorreport3=command("056 INTERNAL SERVER ERROR: INACTIVE SLOTS FOUND\nOne or more anomalies have been archived as inactive. The following changes have been made to account for missing files:\nSCP-048 has been redesignated SCP-001.\nNOTE: The IntSCPFN network has experienced an error. Please report this message along with the error code to the Records and Information Security Administration (RAISA) or email your IntSCPFN server administrator.")
errorreport4=command("001 INTERNAL SERVER ERROR: NO ACTIVE SLOTS FOUND\nNOTE: The IntSCPFN network has experienced an error. Please report this message along with the error code to the Records and Information Security Administration (RAISA) or email your IntSCPFN server administrator.")
classes=command("Reminder object class is not based on how dangerous the SCP is but on how hard it is to contain. The object classes are as follows\nSafe: Object class safe is classified as any SCP that does not make an active effort to escape their containment and is nonhostile to site staff.\nEuclid: Euclid-class SCPs are anomalies that require more resources to contain completely or where containment isn't always reliable. Usually this is because the SCP is insufficiently understood or inherently unpredictable. Euclid is the Object Class with the greatest scope, and it's usually a safe bet that an SCP will be this class if it doesn't easily fall into any of the other standard Object Classes./nAs a note, any SCP that's autonomous, sentient and/or sapient is generally classified as Euclid, due to the inherent unpredictability of an object that can act or think on its own.\n Keter: Keter-class SCPs are anomalies that are exceedingly difficult to contain consistently or reliably, with containment procedures often being extensive and complex. The Foundation often can't contain these SCPs well due to not having a solid understanding of the anomaly, or lacking the technology to properly contain or counter it. A Keter SCP does not mean the SCP is dangerous, just that it is simply very difficult or costly to contain.\nThaumiel: Thaumiel-class SCPs are anomalies that the Foundation specifically uses to contain other SCPs. Even the mere existence of Thaumiel-class objects is classified at the highest levels of the Foundation and their locations, functions, and current status are known to few Foundation personnel outside of the O5 Council.\nNeutralized: Neutralized SCPs are anomalies that are no longer anomalous, either through having been intentionally or accidentally destroyed, or disabled.\nApollyon: Apollyon-class SCPs are anomalies that cannot be contained, are expected to breach containment imminently, or some other similar scenario. Such anomalies are usually associated with world-ending threats or a K-Class Scenario of some kind and require a massive effort from the Foundation to deal with.\nArchon: Archon-class SCPs are anomalies that could theoretically be contained but are best left uncontained for some reason. Archon SCPs may be a part of consensus reality that is difficult to fully contain or may have adverse effects if put into containment. These SCPs are not uncontainable—the defining feature of the class is that the Foundation chooses to not put the anomaly into containment.\nIf you have trouble remembering the class please refer to the locked box test:If you can lock it in a box and nothing happens it is Safe\nIf you lock it in a box and you are unaware of what might happen it is Euclid\nIf you lock it in a box and it escapes it is Keter\nIf it is the box it is Thaumiel\nIf you can't lock it in a box and it tries to end the world it is Apollyon\nIf you can lock it in a box but choose not to it is Archon.", aliases = ["class"]) 
amnestics=command("Both the Foundation and its predecessor organizations have relied on memory affecting agents in order to expunge sensitive data from the minds of unauthorized individuals. Though we have generally classified such agents under the umbrella term ‘amnestics’ (and less accurately, amnesiacs), we have, in fact, used a wide variety of different agents to accomplish this task.\nMany of our commonly used amnestics are themselves anomalous, either in origin or mechanism. The fact that amnestics are frequently anomalies themselves effectively renders them Thaumiel class SCPs, recklessly handed out to any MTF, Field Agent, or Researcher who wants them. Furthermore, the collection of these amnestics are often either fraught with danger or are otherwise ethically problematic.\nFortunately, neuroscience has advanced significantly since the Foundation was founded, and we now have the means to mass produce non-anomalous amnestic drugs. In addition to being wholly non-anomalous, the next generation of amnestic drugs is expected to be more cost-effective for the Foundation and boast a better safety profile for their subjects. These drugs function primarily by inducing memory deconsolidation, breaking down the neural pathways responsible for encoding episodic memories. The drugs themselves are encased within specially designed nanoparticles, allowing for the targeting of specific areas of the brain, drastically reducing the amount of drug required as well as side effects.\nThe O5 Council is currently reviewing proposals to gradually phase out the use of traditional amnestics and replace them with non-anomalous alternatives. In order to facilitate this transition among Foundation personnel, we submit the following revisions to the current amnestics classification system. Please note that all classes of amnestics are now available in oral, inhalant, and intravenous forms for the convenience of amnestics officers, and still retain the taste of batteries and peppermint that none of us can remember but always find familiar.")
amnesticclassa=command("Class A, General Retrograde\n*For erasing recent and/or specific episodic memories*\nWhile Class A amnestics will technically deconsolidate memories at random, they will mostly affect engrams within the ‘memory reconsolidation window’ of 5-6 hours, as these are the memories that will be at the forefront of the subject’s mind. This is especially true for highly unique episodic memories, such as encounters with anomalous phenomena. While these will be most effective after initial exposure, it is possible to re-open a memory reconsolidation window, allowing for amnestics officers to trigger and then erase specific memories long after their initial formation.",aliases=["classa","generalretrograde"])
amnesticclassb=command("Class B, Regressive Retrograde\n*For the incremental erasure of recent memories*\nClass B amnestics start by deconsolidating the most recently formed memories first, and then working their way backwards. The extent of the memory erasure is dependent on dosage, with a 75 mg dose resulting in approximately 24 hours of memory loss on average. These are ideal for erasing recent memories older than six hours without having to trigger specific memories.",aliases=["classb","regressiveretrograde"])
amnesticclassc=command("Class C, Targeted Retrograde\n*For the removal of specific memories from any point in the subject's life*\nClass C amnestics are used in conjunction with high fidelity neuro-imaging and transcranial stimulation. Neuro-imagers will locate the specific memory engrams within the subject’s brain, and upon reaching those specific engrams the amnestics will be activated through the use of precise, non-invasive stimulation, typically ultrasound or magnetic fields.\nThe benefit of Class C amnestics is that they allow for the surgically precise removal of memories regardless of when they formed, and are ideal for expunging classified data from the minds of D-class personnel and neutralized humanoid SCPs prior to their release. The major drawback of Class C amnestics is the required equipment’s lack of portability. As such, Class C amnestics are most efficiently administered at Foundation sites, though mobile amnestic field clinics are currently under development.",aliases=["classc","targetedretrograde"])
amnesticclassd=command("Class D, Progressive Retrograde\n*For the removal of early memories*\nClass D amnestics are the opposite of Class Bs. They target the oldest memories first and work their way forward, the effects depending on dosage. As this is a fairly niche application, Class D amnestics are rarely used. Though they are, by design, more potent than their counterparts, it still requires an extremely high dosage to expunge a significant portion of a subject’s life. As such, their risk of side effects is dangerously high. It should be noted that Class D amnestics only target explicit memories. Implicit memories, namely skills that the individual learned in their youth, will remain unaffected.",aliases=["classd","progressiveretrograde"])
amnesticclasse=command("Class E, Ennui\n*To induce psychological complacency with the anomalous*\nTo be frank, ‘ennui’ isn’t actually the proper term for the psychological effects of Class E amnestics. They would more accurately be considered an ‘anti-nostalgia’ drug. Though they still target the neural pathways for memories, they do not deconsolidate them. Rather, they merely weaken the pathways while disassociating the memory with any emotions, positive or negative, removing any incentive to think about it and thus allowing it to naturally decay on its own.\nClass E amnestics are most effective in situations where the suppression of the anomalous is not possible, and thus in order to preserve normality, the anomaly must be perceived as normal. Class E amnestics cause subjects to accept the world as it is, and forget that it was ever any different.",aliases=["classe","ennui"])
amnesticclassf=command("Class F, Fugue\n*For erasing and rebuilding the subject's identity*\nAs with the old Class F, these amnestics induce a Fugue State, or dissociative amnesia, in the subject. The subject will forget their identity and may either be provided with a new one by the amnestics officer, or allowed to develop one on their own.",aliases=["classf","fugue"])
amnesticclassg=command("Class G, Gaslighting\n*To cause subjects to doubt the authenticity of their memories*\nClass G amnestics induce derealisation of memories, making them seem fantastic or dreamlike, causing the subject to doubt their authenticity. Standard field Class-G amnestics are formulated to target memories of the anomalous, and are best administered when the subject lacks any tangible evidence of their account and targeting specific memories is infeasible. Class-G amnestics that target non-anomalous memories, however, ~~have been banned by the Ethics Committee~~ are currently under development at the request of the O5 Council.",aliases=["classg","gaslighting"])
amnesticclassh=command("Class H, Anterograde\n*To prevent the formation of new memories*\nClass H amnestics prevent the subject from forming new memories, blocking memory consolidation for as long as the agent is in the subject’s system. Duration is dependent on dosage, with 75 mg lasting for approximately 24 hours on average.",aliases=["classh","anterograde"])
amnesticclassi=command("Class I, Transient\n*For inducing a temporary amnesic state*\nClass I amnestics induce transient amnesia by blocking the neural pathways responsible for long-term memories, temporarily preventing subjects from recalling their past. Duration is dependent on dosage, again with 75 mg lasting approximately 24 hours on average.",aliases=["classi","transient"])
mnestics=command("Class W-Z, Mnestics\n*Protection against anti-memetic and other mnemonic anomalies*\nClasses W-Z refer to mnestic drugs, or drugs that prevent/reverse memory erasure, and are most commonly used by the antimemetics department. Though in function they are the opposite of amnestics, they both work by targeting the neural pathways for memory, allowing for the creation of non-anomalous mnestic drugs.\nClass W mnestics allow the subject to perceive and retain knowledge of antimemes, in addition to general memory enhancement. Class X restores awareness of previously perceived antimemes or suppressed memories. Class Y grants the subject perfect recall for any memories gained during its period of effect, and a single dose of Class Z renders the subject biochemically incapable of forgetting anything for the remainder of their lives. Class Zs are invariably fatal, with death by seizure typically resulting in a matter of hours.\nCombining amnestic and mnestic drugs is not recommended.",aliases=["classw","classx","classy","classz"])
amnesticsethicalreport=command("Report to Overseer Council Regarding the Ethics of Non-Anomalous Amnestics\nOverseers,\nThough I am well aware of the numerous ethical and practical drawbacks of conventional amnestics, I regret to inform you that a previously unforeseen complication of non-anomalous amnestics has recently come to light.\nThe very fact that they are non-anomalous makes it possible for civilians to create their own crude amnestic drugs. How the formulas were leaked is still being investigated, but the fact remains that people are now cooking up street amnestics in improvised labs like crystal meth.\nSexual assault is, as one would imagine, the most common crime it is implicated in, but it's no doubt used to cover up all sorts of abuse; criminal, corporate, and government alike. Some people take it willingly to try to expunge their own unwanted memories, but even then the strength of the street formulas vary wildly. Individuals who overdose will end up with enormous chunks of random memories missing, sometimes crucial implicit memories and are reduced to vegetative states. Bad batches are all too common, resulting in permanent brain damage or even death. Rumours of how they are being used by numerous authoritarian regimes are rampant, but since I wasn't able to confirm any of these horror stories myself I won't bother repeating them here.\nThe media has dubbed this outbreak of amnestics abuse \"The Forgotten Epidemic\", and it's our fault. We made this stuff, and it's because of our negligence it's on the streets. Surely we have some responsibility to ameliorate this abuse. I recommend that we delay the full implementation of non-anomalous amnestics until we have determined the source of the security breach and taken measures to prevent a second occurrence in the future. The Foundation should fund the efforts of law enforcement to track down street amnestic producers, and then administer Class-C amnestics to wipe the formulas from their minds.\nThe old amnestics may not have been perfect, but the human cost of using them has already been dwarfed by their non-anomalous equivalents. If we make it a priority, we can get this stuff off the street and bring the Forgotten Epidemic to an end.\n~ Doctor ███████\nDoctor ███████\nThank you for bringing this matter to our attention. As regrettable as this situation may be, the fact that these street amnestics are non-anomalous places their illicit use well outside the Foundation's authority.\nBy unanimous vote, the O5 council has decided that the new generation of non-anomalous amnestics will be deployed as scheduled, and that no Foundation resources will be diverted to prevent or regulate their use among civilians.\n~ O5-4")
clearance=command("""Overview

Foundation security clearances granted to personnel represent the highest level or type of information to which they can be granted access. However, having any given clearance level does not automatically grant access to all information at that level: personnel are only granted access to information on a "need-to-know" basis and at the discretion of the designated disclosure officer overseeing their respective departments.

Level 0 (For Official Use Only)
Level 0 security clearances are given to non-essential personnel with no need to access information regarding anomalous objects or entities in Foundation containment. Level 0 access is typically held by personnel in non-secured clerical, logistics, or janitorial positions at facilities with no access to operational data.

Level 1 (Confidential)
Level 1 security clearances are given to personnel working in proximity to but with no direct, indirect, or informational access to anomalous objects or entities in containment. Level 1 security clearances are typically granted to personnel working in clerical, logistics, or janitorial positions at facilities with containment capability or otherwise must handle sensitive information.

Level 2 (Restricted)
Level 2 security clearances are given to security and research personnel that require direct access to information regarding anomalous objects and entities in containment. Most research staff, field agents, and containment specialists hold a Level 2 security clearance.

Level 3 (Secret)
Level 3 security clearances are given to senior security and research personnel that require in-depth data regarding the source, recovery circumstances, and long-term planning for anomalous objects and entities in containment. Most senior research staff, project managers, security officers, response team members, and Mobile Task Force operatives hold a Level 3 security clearance.

Level 4 (Top Secret)
Level 4 security clearances are given to senior administration that require access to site-wide and/or regional intelligence as well as long-term strategic data regarding Foundation operations and research projects. Level 4 security clearances are typically only held by Site Directors, Security Directors, or Mobile Task Force Commanders.

Level 5 (Thaumiel)
Level 5 security clearances are given to the highest-ranking administrative personnel within the Foundation and grant effectively unlimited access to all strategic and otherwise sensitive data. Level 5 security clearances are typically only granted to O5 Council members and selected staff.""",aliases=["securityclearance"])
personnelclasses=command("""Personnel Classifications

Classifications are assigned to personnel based on their proximity to potentially dangerous anomalous objects, entities, or phenomena.

Class A
Class A personnel are those deemed essential to Foundation strategic operations, and are not allowed direct access to anomalies under any circumstances. When circumstances require Class A personnel to be in direct proximity to such anomalies (such as in the case of facilities housing containment units), Class A personnel are not allowed access to the areas of the facility containing such anomalies and are to be kept in secured areas at all times. In the case of an emergency, Class A personnel are to be immediately evacuated to a designated and secure off-site location. O5 Council members are always Class A personnel.

Class B
Class B personnel are those deemed essential to local Foundation operations, and may only be granted access to objects, entities, and anomalies that have passed quarantine and have been cleared of any potential mind-affecting effects or memetic agents. In the event of a containment breach or hostile action against a Foundation facility, Class B personnel are to be evacuated to a designated, secure off-site location as soon as possible.

Class C
Class C personnel are personnel with direct access to most anomalies not deemed strictly hostile or dangerous. Class C personnel that have had direct contact with potentially mind-affecting or memetic properties may be subject to mandatory quarantine and psychiatric evaluation as deemed necessary by security personnel. In the event of a containment breach or hostile action against a Foundation facility, non-combatant Class C personnel are to either report to secure lock-down areas or evacuated at the discretion of on-site security personnel in the case of a site-wide breach or other catastrophic event.

Class D
Class D personnel are expendable personnel used to handle extremely hazardous anomalies and are not allowed to come into contact with Class A or Class B personnel. Class D personnel are typically drawn worldwide from the ranks of prison inmates convicted of violent crimes, especially those on death row. In times of duress, Protocol 12 may be enacted, which allows recruitment from other sources — such as political prisoners, refugee populations, and other civilian sources — that can be transferred into Foundation custody under plausibly deniable circumstances. Class D personnel are to be given regular mandatory psychiatric evaluations and are to be administered an amnestic of at least Class B strength or terminated at the end of the month at the discretion of on-site security or medical staff. In the event of a catastrophic site event, Class D personnel are to be terminated immediately except as deemed necessary by on-site security personnel.

Class E
Class E is a provisional classification applied to field agents and containment personnel that have been exposed to potentially dangerous effects during the course of securing and establishing initial containment over a newly-designated anomalous object, entity, or phenomenon. Class E personnel are to be quarantined as soon as possible, monitored, and screened for potentially harmful changes in behavior, personality, or physiology, and may only return to duty after being fully debriefed and cleared by psychiatric and medical staff.""")
stafftitles=command("""Staff Titles

These are general occupational titles that are typically used in the Foundation.

Site Staff
Containment Specialist
Containment specialists have two main roles at Foundation facilities. Firstly, containment teams are called upon to respond to confirmed cases of anomalous activity to secure and establish initial containment over anomalous objects, entities, or phenomena and transport them to the nearest Foundation containment site.

In addition, Foundation containment engineers and technicians are called upon to devise, refine, and maintain containment units and schemes for objects, entities, and phenomena in Foundation facilities.

Researcher
Researchers are the scientific branch of the Foundation, drawn from the ranks of the smartest and best-trained research scientists from around the world. With specialists in every field imaginable, from chemistry and botany to more esoteric or specialized fields such as theoretical physics and xenobiology, the goal of the Foundation's research projects is to gain a better understanding of unexplained anomalies and how they operate.

Security Officer
On-site security officers — often referred to simply as guards — at Foundation facilities are tasked with maintaining physical and information security for Foundation projects, operations, and personnel. Primarily drawn and recruited from military, law enforcement, and correctional facility personnel, security officers are trained in the use of all types of weapons as well as a variety of contingency plans covering both containment breach incidents as well as hostile action. These personnel are also responsible for information security, such as making sure that sensitive documents are not misplaced and that a facility's computer systems are safe from outside intrusion. They are also often the first line of defense against hostile outside forces for Foundation facilities.

Tactical Response Officer
Response teams — or tactical teams — are highly trained and heavily armed combat teams tasked with escorting containment teams when dangerous anomalous entities or hostile Groups of Interest are involved and defending Foundation facilities against hostile action. Response teams are effectively military units stationed at major Foundation facilities that are ready to deploy at a moment's notice.

Field Personnel
Field Agent
Field agents are the eyes and ears of the Foundation, personnel trained to look for and investigate signs of anomalous activity, often undercover with local or regional law enforcement or embedded in local services such as emergency medical services and regulatory organizations. As undercover units, field agents are typically not equipped to deal with confirmed cases of anomalous activity; once such an incident has been confirmed and isolated, field agents will typically call for assistance from the nearest field containment team with the means to safely secure and contain such anomalies.

Mobile Task Force Operative
Mobile Task Forces are specialist units comprised of veteran field personnel drawn from all over the Foundation. These task forces are mobilized to deal with threats of a specific nature and can include anything from field researchers specializing in a particular type of anomaly to heavily armed combat units tasked to secure certain types of hostile anomalous entity. See the Task Forces document for more detailed information.

Administration
Site Director
Site directors for major Foundation facilities are the highest-ranking personnel at that location and are responsible for the continued, safe operation of the site and all of its contained anomalies and projects. All major departmental directors report directly to the Site Director, who in turn reports to the O5 Council.

O5 Council Member
The O5 Council refers to the committee consisting of the highest-ranking directors of the Foundation. With complete access to all information regarding anomalies in containment, the O5 Council oversees all Foundation operations worldwide and directs its long-term strategic plans. Due to the sensitivity of their positions, O5 Council members must not come into direct contact with any anomalous object, entity, or phenomenon. Furthermore, the identities of all O5 Council members is classified; all council members are referred to only by their numeric designation (O5-1 through O5-13).""",aliases=["titles"])
